### ISSUE TITLE
Compatibility issue w/CiviCRM 4.6.18 (was: Certain situations create bad xml files)

### ISSUE THREAD

**Issue by Detsieber** [sfe-ev/ssepa#4]
Using CiviCRM 4.6.18 (or maybe earlier?), bad xml files are created.

Errors are:
`<PmtInfId></PmtInfId>` is empty
 `<SeqTp></SeqTp>`  is empty
`<ReqdColltnDt></ReqdColltnDt>` is empty

If the xml file contains more than one group, the following groups are marked CORE, although it should read COR1.

**Comment by antrik** [comment]
I found the first problem: a typo (I presume?) in some of the ancient code (that I never quite understood what it is for) suddenly became meaningful due to some CiviCRM change, and made a SEPA API call fail; and because of missing error handling in another ancient code part, it was just failing silently, instead of generating an error message... Fixing this avoids the unpopulated fields.

This is precisely why I don't feel comfortable officially releasing this extension until all this ancient code gets thoroughly reviewed and fixed up.

All groups are still generated with `CORE` though (no `COR1`) -- so I guess there is yet another issue...

**Comment by antrik** [comment]
Weird, `COR1` actually seems to work fine now... Unless it's an intermittent issue (I hope not), I probably just mixed something up... I hate manual testing :-(

**Comment by Detsieber** [comment]
Can I help testing?

**Comment by antrik** [comment]
@Detsieber I put it on `civitest` now; if it looks good, I'll roll a 0.4.1 release, and we can put it in production...

**Comment by Detsieber** [comment]
Thank you - this looks fine and works well!  Please roll out an 0.4.1 release, since this will make it much easier for me to produce tomorrows SEPA files!

Just one minor point: 
Generate Recurring Payments throws a notice:
"Notice: Undefined index: contribution_contact_id in _civicrm_api3_contribution_get_spec() (line 262 of /mnt/dc-www/dcivi/sites/all/modules/civicrm/api/v3/Contribution.php)."

**Comment by antrik** [comment]
@Detsieber is this notice new? It sounds unrelated... (I know there have been a number of warnings before, but don't remember which.)

**Comment by Detsieber** [comment]
I am not sure if this notice is New...

Am 9. November 2016 00:22:43 MEZ, schrieb Olaf Buddenhagen notifications@github.com:

> @Detsieber is this notice new? It sounds unrelated... (I know there
> have been a number of warnings before, but don't remember which.)
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/sfe-ev/ssepa/issues/4#issuecomment-259291453

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by antrik** [comment]
@Detsieber I'd say file a separate issue?...

**Comment by antrik** [comment]
@Detsieber uploaded `sfe-0.4.1`.

**Comment by Detsieber** [comment]
Problem is solved with 0.4.1 !
